
[CARS]
;0 == Citroen Xsara 00
;1 == Hyundai Accent 00
;2 == MG ZR Super 1600
;3 == Mitsubishi Lancer Evo VII
;4 == Peugeot 206 99
;5 == Subaru Impreza 2001 A8
;6 == Toyota Corolla 98
;7 == Toyota Corolla 98

; you don't need to enter the path . all engines in audio\cars directory (current dir)
; IMPORTANT
; no space between the = sign and carsound name

InsideCutFrequency=750.0

Car0=subaru
Car0_LowShelfAmp=2.0
Car0_LowShelfFrequency=200.0

Car1=subaru
Car1_LowShelfAmp=2.0
Car1_LowShelfFrequency=200.0

Car2=subaru
Car2_LowShelfAmp=2.0
Car2_LowShelfFrequency=200.0

Car3=subaru
Car3_LowShelfAmp=2.0
Car3_LowShelfFrequency=200.0

Car4=subaru
Car4_LowShelfAmp=2.0
Car4_LowShelfFrequency=200.0

Car5=subaru
Car5_LowShelfAmp=2.0
Car5_LowShelfFrequency=200.0

Car6=subaru
Car6_LowShelfAmp=2.0
Car6_LowShelfFrequency=200.0

Car7=subaru
Car7_LowShelfAmp=2.0
Car7_LowShelfFrequency=200.0
