[SOUNDDEF::EXHAUST]
; main engine sound
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 40.0
MaxDistance = 100.0

[SOUNDDEF::EXHAUSTPOP]
; main engine sound
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 20.0
MaxDistance = 50.0

[SOUNDDEF::TRANSMISSION]
; transmission sound
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 5.0
MaxDistance = 20.0

[SOUNDDEF::TIRE]
; tire sound
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 40.0

[SOUNDDEF::TURBO]
; tire sound
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 50.0

[SOUNDDEF::BLOWOFFVALVE]
; tire sound
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 50.0

;Impacts

[SOUNDDEF::GRAVEL]
; Gravel hitting wheelhouse
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 3.0
MaxDistance = 10.0

[SOUNDDEF::SOFTMETAL]
; Soft impact
Volume = 0.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 30.0

[SOUNDDEF::SHATTER]
; Addon sound when high impact power
Volume = 0.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 50.0

[SOUNDDEF::GLASS]
; Addon sound when high impact power
Volume = 0.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 30.0

[SOUNDDEF::BRANCH]
; Addon sound when high impact power
Volume = 0.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 30.0

[SOUNDDEF::SOFTHIT]
; Addon sound when high impact power
Volume = 0.0
OutsideVolume = 0.0
MinDistance = 1.0
MaxDistance = 2.0

[SOUNDDEF::MEDIUMHIT]
; Addon sound when high impact power
Volume = 0.0
OutsideVolume = 0.0
MinDistance = 10.0
MaxDistance = 30.0

[SOUNDDEF::HARDHIT]
; Addon sound when high impact power
Volume = 0.0
OutsideVolume = 0.0
MinDistance = 3.0
MaxDistance = 50.0

[SOUNDDEF::RANGED]
; ranged impact
Volume = 1.0
OutsideVolume = 0.0
MinDistance = 3.0
MaxDistance = 100.0