[MUSICPC::FRONTEND]
Music =Audio\Music\ba.ogg

[MUSICPC::SERVICEPARK]
Music =Audio\Music\sp.ogg

[MUSICPC::PRIZECERMONY]
Music =Audio\Music\ba.ogg

[MUSICPC::REPLAY]
;Music41  Meaning replay music on track 41 only if Random is false
;Lines below defines the diffrent music to have almost have an equal chance to be played
Random = true
#Music00 =Audio\Music\The Desert Sessions - A#1.ogg
#Music10 =Audio\Music\regular john.ogg
#Music20 =Audio\Music\juice.ogg
#Music30 =Audio\Music\brazenhead.ogg
#Music40 =Audio\Music\jwalking.ogg
#Music50 =Audio\Music\nwo.ogg
#Music60 =Audio\Music\ethernal.ogg
#Music70 =Audio\Music\Nuclear Guru.ogg
#Music80 =Audio\Music\Smea - Test 2.ogg
#Music90 =Audio\Music\Primus.ogg
Music00 =Audio\Music\ba.ogg
Music20 =Audio\Music\cy.ogg
Music40 =Audio\Music\go.ogg
Music60 =Audio\Music\creep.ogg
Music80 =Audio\Music\gt.ogg